#! /bin/sh

# update with the correct path of your logstash
# Logstash is by default a bit too talkative
/opt/logstash/bin/logstash --log.level error --path.settings /etc/logstash/ $* | grep -v "ipeline"
